// Generated by js_of_ocaml 4.0.0
(function(a){typeof
globalThis!=="object"&&(this?b():(a.defineProperty(a.prototype,"_T_",{configurable:true,get:b}),_T_));function
b(){var
b=this||self;b.globalThis=b;delete
a.prototype._T_}}(Object));(function(a){"use strict";var
al=" : flags Open_text and Open_binary are not compatible",ar="Sys_error",aC="Invalid_argument",I="rmdir",af=0xf0,D='"',aB=0x800,aq="EEXIST",aA="jsError",w=1024,az="End_of_file",ad="Pervasives.do_at_exit",ae="utf8",K="Unix.Unix_error",k=0x80,O="Failure",ac="Undefined_recursive_module",ap=" : flags Open_rdonly and Open_wronly are not compatible",J="mkdir",ay="\n",ao=512,ak="Stack_overflow",c="",N="ENOENT",aj="^",C=": No such file or directory",L=": Not a directory",ab=0xe0,ai="/static/",an=" : file already exists",ax="([^/]+)",t=0x3f,aa=0xdfff,ah="Not_found",$="Assert_failure",l="/",M=128,au="Sys_blocked_io",av="fd ",aw=0xdc00,am="Out_of_memory",at="ENOTEMPTY",H="ENOTDIR",ag="Match_failure",i=248,as="Division_by_zero";function
T(d,b,a){var
e=String.fromCharCode;if(b==0&&a<=4096&&a==d.length)return e.apply(null,d);var
f=c;for(;0<a;b+=w,a-=w)f+=e.apply(null,d.slice(b,b+Math.min(a,w)));return f}function
Q(c){if(a.Uint8Array)var
d=new(a.Uint8Array)(c.l);else
var
d=new
Array(c.l);var
f=c.c,e=f.length,b=0;for(;b<e;b++)d[b]=f.charCodeAt(b);for(e=c.l;b<e;b++)d[b]=0;c.c=d;c.t=4;return d}function
x(d,e,b,f,c){if(c==0)return 0;if(f==0&&(c>=b.l||b.t==2&&c>=b.c.length)){b.c=d.t==4?T(d.c,e,c):e==0&&d.c.length==c?d.c:d.c.substr(e,c);b.t=b.c.length==b.l?0:2}else
if(b.t==2&&f==b.c.length){b.c+=d.t==4?T(d.c,e,c):e==0&&d.c.length==c?d.c:d.c.substr(e,c);b.t=b.c.length==b.l?0:2}else{if(b.t!=4)Q(b);var
g=d.c,h=b.c;if(d.t==4)if(f<=e)for(var
a=0;a<c;a++)h[f+a]=g[e+a];else
for(var
a=c-1;a>=0;a--)h[f+a]=g[e+a];else{var
i=Math.min(c,g.length-e);for(var
a=0;a<i;a++)h[f+a]=g.charCodeAt(e+a);for(;a<c;a++)h[f+a]=0}}return 0}function
y(a){return a}function
P(a,b,c,d,e){x(y(a),b,c,d,e);return 0}function
bk(b,a){if(b==0)return c;if(a.repeat)return a.repeat(b);var
e=c,d=0;for(;;){if(b&1)e+=a;b>>=1;if(b==0)return e;a+=a;d++;if(d==9)a.slice(0,1)}}function
aH(a){if(a.t==2)a.c+=bk(a.l-a.c.length,"\0");else
a.c=T(a.c,0,a.c.length);a.t=0}function
aV(a){if(a.length<24){for(var
b=0;b<a.length;b++)if(a.charCodeAt(b)>127)return false;return true}else
return!/[^\x00-\x7f]/.test(a)}function
U(f){for(var
l=c,d=c,h,g,i,a,b=0,j=f.length;b<j;b++){g=f.charCodeAt(b);if(g<k){for(var
e=b+1;e<j&&(g=f.charCodeAt(e))<k;e++);if(e-b>ao){d.substr(0,1);l+=d;d=c;l+=f.slice(b,e)}else
d+=f.slice(b,e);if(e==j)break;b=e}a=1;if(++b<j&&((i=f.charCodeAt(b))&-64)==M){h=i+(g<<6);if(g<ab){a=h-0x3080;if(a<k)a=1}else{a=2;if(++b<j&&((i=f.charCodeAt(b))&-64)==M){h=i+(h<<6);if(g<af){a=h-0xe2080;if(a<aB||a>=0xd7ff&&a<0xe000)a=2}else{a=3;if(++b<j&&((i=f.charCodeAt(b))&-64)==M&&g<0xf5){a=i-0x3c82080+(h<<6);if(a<0x10000||a>0x10ffff)a=3}}}}}if(a<4){b-=a;d+="\ufffd"}else
if(a>0xffff)d+=String.fromCharCode(0xd7c0+(a>>10),aw+(a&0x3FF));else
d+=String.fromCharCode(a);if(d.length>w){d.substr(0,1);l+=d;d=c}}return l+d}function
m(c,a,b){this.t=c;this.c=a;this.l=b}m.prototype.toString=function(){switch(this.t){case
9:return this.c;default:aH(this);case
0:if(aV(this.c)){this.t=9;return this.c}this.t=8;case
8:return this.c}};m.prototype.toUtf16=function(){var
a=this.toString();if(this.t==9)return a;return U(a)};m.prototype.slice=function(){var
a=this.t==4?this.c.slice():this.c;return new
m(this.t,a,this.l)};function
bh(b,a){throw[0,b,a]}function
aF(a){return new
m(0,a,a.length)}function
e(a){return aF(a)}function
S(b,a){bh(b,e(a))}var
d=[0];function
aL(a){S(d.Invalid_argument,a)}function
p(a){if(a<0)aL("Bytes.create");return new
m(a?2:9,c,a)}function
aI(a){if(!d.Failure)d.Failure=[i,e(O),-3];S(d.Failure,a)}function
ba(a){return a.toUtf16()}function
B(){return typeof
a.process!=="undefined"&&typeof
a.process.versions!=="undefined"&&typeof
a.process.versions.node!=="undefined"}function
bq(){function
b(a){if(a.charAt(0)===l)return[c,a.substring(1)];return}function
d(d){var
h=/^([a-zA-Z]:|[\\/]{2}[^\\/]+[\\/]+[^\\/]+)?([\\/])?([\s\S]*?)$/,a=h.exec(d),b=a[1]||c,f=Boolean(b&&b.charAt(1)!==":");if(Boolean(a[2]||f)){var
e=a[1]||c,g=a[2]||c;return[e,d.substring(e.length+g.length)]}return}return B()&&a.process&&a.process.platform?a.process.platform==="win32"?d:b:b}var
V=bq();function
aT(a){return a.slice(-1)!==l?a+l:a}if(B()&&a.process&&a.process.cwd)var
z=a.process.cwd().replace(/\\/g,l);else
var
z="/static";z=aT(z);function
bb(a){a=ba(a);if(!V(a))a=z+a;var
e=V(a),d=e[1].split(l),b=[];for(var
c=0;c<d.length;c++)switch(d[c]){case"..":if(b.length>1)b.pop();break;case".":break;default:b.push(d[c]);break}b.unshift(e[0]);b.orig=a;return b}function
bm(f){for(var
g=c,b=g,a,i,d=0,h=f.length;d<h;d++){a=f.charCodeAt(d);if(a<k){for(var
e=d+1;e<h&&(a=f.charCodeAt(e))<k;e++);if(e-d>ao){b.substr(0,1);g+=b;b=c;g+=f.slice(d,e)}else
b+=f.slice(d,e);if(e==h)break;d=e}if(a<aB){b+=String.fromCharCode(0xc0|a>>6);b+=String.fromCharCode(k|a&t)}else
if(a<0xd800||a>=aa)b+=String.fromCharCode(ab|a>>12,k|a>>6&t,k|a&t);else
if(a>=0xdbff||d+1==h||(i=f.charCodeAt(d+1))<aw||i>aa)b+="\xef\xbf\xbd";else{d++;a=(a<<10)+i-0x35fdc00;b+=String.fromCharCode(af|a>>18,k|a>>12&t,k|a>>6&t,k|a&t)}if(b.length>w){b.substr(0,1);g+=b;b=c}}return g+b}function
a4(a){var
b=9;if(!aV(a))b=8,a=bm(a);return new
m(b,a,a.length)}function
u(a){return a4(a)}var
br=["E2BIG","EACCES","EAGAIN","EBADF","EBUSY","ECHILD","EDEADLK","EDOM",aq,"EFAULT","EFBIG","EINTR","EINVAL","EIO","EISDIR","EMFILE","EMLINK","ENAMETOOLONG","ENFILE","ENODEV",N,"ENOEXEC","ENOLCK","ENOMEM","ENOSPC","ENOSYS",H,at,"ENOTTY","ENXIO","EPERM","EPIPE","ERANGE","EROFS","ESPIPE","ESRCH","EXDEV","EWOULDBLOCK","EINPROGRESS","EALREADY","ENOTSOCK","EDESTADDRREQ","EMSGSIZE","EPROTOTYPE","ENOPROTOOPT","EPROTONOSUPPORT","ESOCKTNOSUPPORT","EOPNOTSUPP","EPFNOSUPPORT","EAFNOSUPPORT","EADDRINUSE","EADDRNOTAVAIL","ENETDOWN","ENETUNREACH","ENETRESET","ECONNABORTED","ECONNRESET","ENOBUFS","EISCONN","ENOTCONN","ESHUTDOWN","ETOOMANYREFS","ETIMEDOUT","ECONNREFUSED","EHOSTDOWN","EHOSTUNREACH","ELOOP","EOVERFLOW"];function
s(e,g,f,a){var
b=br.indexOf(e);if(b<0){if(a==null)a=-9999;b=[0,a]}var
d=[b,u(g||c),u(f||c)];return d}var
aP={};function
q(a){return aP[a]}function
r(b,a){throw[0,b].concat(a)}function
aM(a){return a
instanceof
m}function
a_(a){return aM(a)}function
a3(a){return new
m(4,a,a.length)}function
b(a){S(d.Sys_error,a)}function
bg(a){b(a+C)}function
aE(){aL("index out of bounds")}function
aG(a,b){switch(a.t&6){default:if(b>=a.c.length)return 0;case
0:return a.c.charCodeAt(b);case
4:return a.c[b]}}function
a2(b,a){if(a>>>0>=b.l)aE();return aG(b,a)}function
R(a){return a.l}function
aD(){}function
f(a){this.data=a}f.prototype=new
aD();f.prototype.truncate=function(a){var
b=this.data;this.data=p(a|0);x(b,0,this.data,0,a)};f.prototype.length=function(){return R(this.data)};f.prototype.write=function(b,d,g,a){var
c=this.length();if(b+a>=c){var
e=p(b+a),f=this.data;this.data=e;x(f,0,this.data,0,c)}P(d,g,this.data,b,a);return 0};f.prototype.read=function(c,a,d,b){var
e=this.length();x(this.data,c,a,d,b);return 0};f.prototype.read_one=function(a){return a2(this.data,a)};f.prototype.close=function(){};f.prototype.constructor=f;function
h(b,a){this.content={};this.root=b;this.lookupFun=a}h.prototype.nm=function(a){return this.root+a};h.prototype.create_dir_if_needed=function(e){var
d=e.split(l),b=c;for(var
a=0;a<d.length-1;a++){b+=d[a]+l;if(this.content[b])continue;this.content[b]=Symbol("directory")}};h.prototype.slash=function(a){return/\/$/.test(a)?a:a+l};h.prototype.lookup=function(a){if(!this.content[a]&&this.lookupFun){var
b=this.lookupFun(e(this.root),e(a));if(b!==0){this.create_dir_if_needed(a);this.content[a]=new
f(y(b[1]))}}};h.prototype.exists=function(a){if(a==c)return 1;var
b=this.slash(a);if(this.content[b])return 1;this.lookup(a);return this.content[a]?1:0};h.prototype.mkdir=function(e,g,f){var
d=f&&q(K);if(this.exists(e))if(d)r(d,s(aq,J,this.nm(e)));else
b(e+": File exists");var
a=/^(.*)\/[^/]+/.exec(e);a=a&&a[1]||c;if(!this.exists(a))if(d)r(d,s(N,J,this.nm(a)));else
b(a+C);if(!this.is_dir(a))if(d)r(d,s(H,J,this.nm(a)));else
b(a+L);this.create_dir_if_needed(this.slash(e))};h.prototype.rmdir=function(a,h){var
d=h&&q(K),e=a==c?c:this.slash(a),g=new
RegExp(aj+e+ax);if(!this.exists(a))if(d)r(d,s(N,I,this.nm(a)));else
b(a+C);if(!this.is_dir(a))if(d)r(d,s(H,I,this.nm(a)));else
b(a+L);for(var
f
in
this.content)if(f.match(g))if(d)r(d,s(at,I,this.nm(a)));else
b(this.nm(a)+": Directory not empty");delete
this.content[e]};h.prototype.readdir=function(a){var
h=a==c?c:this.slash(a);if(!this.exists(a))b(a+C);if(!this.is_dir(a))b(a+L);var
i=new
RegExp(aj+h+ax),f={},e=[];for(var
g
in
this.content){var
d=g.match(i);if(d&&!f[d[1]]){f[d[1]]=true;e.push(d[1])}}return e};h.prototype.is_dir=function(a){if(a==c)return true;var
b=this.slash(a);return this.content[b]?1:0};h.prototype.unlink=function(a){var
b=this.content[a]?true:false;delete
this.content[a];return b};h.prototype.open=function(a,c){if(c.rdonly&&c.wronly)b(this.nm(a)+ap);if(c.text&&c.binary)b(this.nm(a)+al);this.lookup(a);if(this.content[a]){if(this.is_dir(a))b(this.nm(a)+" : is a directory");if(c.create&&c.excl)b(this.nm(a)+an);var
d=this.content[a];if(c.truncate)d.truncate();return d}else
if(c.create){this.create_dir_if_needed(a);this.content[a]=new
f(p(0));return this.content[a]}else
bg(this.nm(a))};h.prototype.register=function(d,a){var
c;if(this.content[d])b(this.nm(d)+an);if(aM(a))c=new
f(a);if(a_(a))c=new
f(y(a));else
if(a
instanceof
Array)c=new
f(a3(a));else
if(typeof
a==="string")c=new
f(aF(a));else
if(a.toString){var
e=y(u(a.toString()));c=new
f(e)}if(c){this.create_dir_if_needed(d);this.content[d]=c}else
b(this.nm(d)+" : registering file with invalid content type")};h.prototype.constructor=h;function
A(a){return R(a)}function
bl(b,a){return aG(b,a)}function
a1(d){var
c=A(d),b=new
Array(c),a=0;for(;a<c;a++)b[a]=bl(d,a);return b}function
a0(a){if(a.t!=4)Q(a);return a.c}function
a6(a,c,b){b&=0xff;if(a.t!=4){if(c==a.c.length){a.c+=String.fromCharCode(b);if(c+1==a.l)a.t=0;return 0}Q(a)}a.c[c]=b;return 0}function
a5(b,a,c){if(a>>>0>=b.l)aE();return a6(b,a,c)}function
n(a){this.fs=require("fs");this.fd=a}n.prototype=new
aD();n.prototype.truncate=function(a){try{this.fs.ftruncateSync(this.fd,a|0)}catch(a){b(a.toString())}};n.prototype.length=function(){try{return this.fs.fstatSync(this.fd).size}catch(a){b(a.toString())}};n.prototype.write=function(h,d,e,g){var
c=a1(d);if(!(c
instanceof
a.Uint8Array))c=new(a.Uint8Array)(c);var
f=a.Buffer.from(c);try{this.fs.writeSync(this.fd,f,e,g,h)}catch(a){b(a.toString())}return 0};n.prototype.read=function(i,f,e,h){var
c=a0(f);if(!(c
instanceof
a.Uint8Array))c=new(a.Uint8Array)(c);var
g=a.Buffer.from(c);try{this.fs.readSync(this.fd,g,e,h,i)}catch(a){b(a.toString())}for(var
d=0;d<h;d++)a5(f,e+d,g[e+d]);return 0};n.prototype.read_one=function(e){var
d=new(a.Uint8Array)(1),c=a.Buffer.from(d);try{this.fs.readSync(this.fd,c,0,1,e)}catch(a){b(a.toString())}return c[0]};n.prototype.close=function(){try{this.fs.closeSync(this.fd)}catch(a){b(a.toString())}};n.prototype.constructor=n;function
g(a){this.fs=require("fs");this.root=a}g.prototype.nm=function(a){return this.root+a};g.prototype.exists=function(a){try{return this.fs.existsSync(this.nm(a))?1:0}catch(a){return 0}};g.prototype.mkdir=function(b,a,c){try{this.fs.mkdirSync(this.nm(b),{mode:a});return 0}catch(a){this.raise_nodejs_error(a,c)}};g.prototype.rmdir=function(a,b){try{this.fs.rmdirSync(this.nm(a));return 0}catch(a){this.raise_nodejs_error(a,b)}};g.prototype.readdir=function(a,b){try{return this.fs.readdirSync(this.nm(a))}catch(a){this.raise_nodejs_error(a,b)}};g.prototype.is_dir=function(a){try{return this.fs.statSync(this.nm(a)).isDirectory()?1:0}catch(a){b(a.toString())}};g.prototype.unlink=function(a,c){try{var
b=this.fs.existsSync(this.nm(a))?1:0;this.fs.unlinkSync(this.nm(a));return b}catch(a){this.raise_nodejs_error(a,c)}};g.prototype.open=function(f,c,g){var
a=require("constants"),b=0;for(var
e
in
c)switch(e){case"rdonly":b|=a.O_RDONLY;break;case"wronly":b|=a.O_WRONLY;break;case"append":b|=a.O_WRONLY|a.O_APPEND;break;case"create":b|=a.O_CREAT;break;case"truncate":b|=a.O_TRUNC;break;case"excl":b|=a.O_EXCL;break;case"binary":b|=a.O_BINARY;break;case"text":b|=a.O_TEXT;break;case"nonblock":b|=a.O_NONBLOCK;break}try{var
d=this.fs.openSync(this.nm(f),b);return new
n(d)}catch(a){this.raise_nodejs_error(a,g)}};g.prototype.rename=function(b,a,c){try{this.fs.renameSync(this.nm(b),this.nm(a))}catch(a){this.raise_nodejs_error(a,c)}};g.prototype.stat=function(b,c){try{var
a=this.fs.statSync(this.nm(b));return this.stats_from_js(a)}catch(a){this.raise_nodejs_error(a,c)}};g.prototype.lstat=function(b,c){try{var
a=this.fs.lstatSync(this.nm(b));return this.stats_from_js(a)}catch(a){this.raise_nodejs_error(a,c)}};g.prototype.symlink=function(d,c,a,b){try{this.fs.symlinkSync(this.nm(c),this.nm(a),d?"dir":"file");return 0}catch(a){this.raise_nodejs_error(a,b)}};g.prototype.readlink=function(b,c){try{var
a=this.fs.readlinkSync(this.nm(b),ae);return u(a)}catch(a){this.raise_nodejs_error(a,c)}};g.prototype.raise_nodejs_error=function(a,e){var
c=q(K);if(e&&c){var
d=s(a.code,a.syscall,a.path,a.errno);r(c,d)}else
b(a.toString())};g.prototype.stats_from_js=function(a){var
b;if(a.isFile())b=0;else
if(a.isDirectory())b=1;else
if(a.isCharacterDevice())b=2;else
if(a.isBlockDevice())b=3;else
if(a.isSymbolicLink())b=4;else
if(a.isFIFO())b=5;else
if(a.isSocket())b=6;return[0,a.dev,a.ino,b,a.mode,a.nlink,a.uid,a.gid,a.rdev,a.size,a.atimeMs,a.mtimeMs,a.ctimeMs]};g.prototype.constructor=g;function
aK(b){var
a=V(b);if(!a)return;return a[0]+l}var
F=aK(z)||aI("unable to compute caml_root"),v=[];if(B())v.push({path:F,device:new
g(F)});else
v.push({path:F,device:new
h(F)});v.push({path:ai,device:new
h(ai)});function
aW(c){var
i=bb(c),c=i.join(l),h=aT(c),d;for(var
f=0;f<v.length;f++){var
a=v[f];if(h.search(a.path)==0&&(!d||d.path.length<a.path.length))d={path:a.path,device:a.device,rest:c.substring(a.path.length,c.length)}}if(!d&&B()){var
e=aK(c);if(e&&e.match(/^[a-zA-Z]:\/$/)){var
a={path:e,device:new
g(e)};v.push(a);d={path:a.path,device:a.device,rest:c.substring(a.path.length,c.length)}}}if(d)return d;b("no device found for "+h)}function
a7(c,b){var
a=aW(c);if(!a.device.register)aI("cannot register file");a.device.register(a.rest,b);return 0}function
aU(b,a){var
b=e(b),a=e(a);return a7(b,a)}function
a9(){var
c=a.caml_fs_tmp;if(c)for(var
b=0;b<c.length;b++)aU(c[b].name,c[b].content);a.jsoo_create_file=aU;a.caml_fs_tmp=[];return 0}var
o=new
Array();function
aN(f){var
a=o[f];if(!a.opened)b("Cannot flush a closed channel");if(!a.buffer||a.buffer==c)return 0;if(a.fd&&d.fds[a.fd]&&d.fds[a.fd].output){var
e=d.fds[a.fd].output;switch(e.length){case
2:e(f,a.buffer);break;default:e(a.buffer)}}a.buffer=c;return 0}function
E(a){a.t&6&&aH(a);return a.c}function
aR(d,f){var
a=o[d],c=e(f),b=A(c);a.file.write(a.offset,c,0,b);a.offset+=b;return 0}function
bo(b){var
b=U(b),c=a;if(c.process&&c.process.stdout&&c.process.stdout.write)c.process.stderr.write(b);else{if(b.charCodeAt(b.length-1)==10)b=b.substr(0,b.length-1);var
d=c.console;d&&d.error&&d.error(b)}}function
bp(b){var
b=U(b),c=a;if(c.process&&c.process.stdout&&c.process.stdout.write)c.process.stdout.write(b);else{if(b.charCodeAt(b.length-1)==10)b=b.substr(0,b.length-1);var
d=c.console;d&&d.log&&d.log(b)}}function
G(c,f,e,a){if(d.fds===undefined)d.fds=new
Array();a=a?a:{};var
b={};b.file=e;b.offset=a.append?e.length():0;b.flags=a;b.output=f;d.fds[c]=b;if(!d.fd_last_idx||c>d.fd_last_idx)d.fd_last_idx=c;return c}function
bs(e,c,i){var
a={};while(c){switch(c[1]){case
0:a.rdonly=1;break;case
1:a.wronly=1;break;case
2:a.append=1;break;case
3:a.create=1;break;case
4:a.truncate=1;break;case
5:a.excl=1;break;case
6:a.binary=1;break;case
7:a.text=1;break;case
8:a.nonblock=1;break}c=c[2]}if(a.rdonly&&a.wronly)b(E(e)+ap);if(a.text&&a.binary)b(E(e)+al);var
f=aW(e),g=f.device.open(f.rest,a),h=d.fd_last_idx?d.fd_last_idx:0;return G(h+1,aR,g,a)}G(0,aR,new
f(p(0)));G(1,bp,new
f(p(0)));G(2,bo,new
f(p(0)));function
bc(a){var
e=d.fds[a];if(e.flags.wronly)b(av+a+" is writeonly");var
f=null;if(a==0&&B()){var
g=require("fs");f=function(){return u(g.readFileSync(0,ae))}}var
c={file:e.file,offset:e.offset,fd:a,opened:true,out:false,refill:f};o[c.fd]=c;return c.fd}function
aO(f){var
e=d.fds[f];if(e.flags.rdonly)b(av+f+" is readonly");var
a={file:e.file,offset:e.offset,fd:f,opened:true,out:true,buffer:c};o[a.fd]=a;return a.fd}function
bd(){var
b=0;for(var
a=0;a<o.length;a++)if(o[a]&&o[a].opened&&o[a].out)b=[0,o[a].fd,b];return b}function
aS(a){return a}function
bf(h,e,i,g){var
c=o[h];if(!c.opened)b("Cannot output to a closed channel");var
a;if(i==0&&R(e)==g)a=e;else{a=p(g);x(e,i,a,0,g)}var
j=aS(a),d=E(j),f=d.lastIndexOf(ay);if(f<0)c.buffer+=d;else{c.buffer+=d.substr(0,f+1);aN(h);c.buffer+=d.substr(f+1)}return 0}function
be(b,a,d,c){return bf(b,y(a),d,c)}function
j(c,e,b){if(b&&a.toplevelReloc)c=a.toplevelReloc(b);d[c+1]=e;if(b)d[b]=e}function
bi(a,b){aP[E(a)]=b;return 0}function
aQ(a){return a}function
bn(b){if(b
instanceof
Array)return b;if(a.RangeError&&b
instanceof
a.RangeError&&b.message&&b.message.match(/maximum call stack/i))return aQ(d.Stack_overflow);if(a.InternalError&&b
instanceof
a.InternalError&&b.message&&b.message.match(/too much recursion/i))return aQ(d.Stack_overflow);if(b
instanceof
a.Error&&q(aA))return[0,q(aA),b];return[0,d.Failure,u(String(b))]}function
a$(a){switch(a[2]){case-8:case-11:case-12:return 1;default:return 0}}function
a8(b){var
a=c;if(b[0]==0){a+=b[1][1];if(b.length==3&&b[2][0]==0&&a$(b[1]))var
f=b[2],g=1;else
var
g=2,f=b;a+="(";for(var
e=g;e<f.length;e++){if(e>g)a+=", ";var
d=f[e];if(typeof
d=="number")a+=d.toString();else
if(d
instanceof
m)a+=D+d.toString()+D;else
if(typeof
d=="string")a+=D+d.toString()+D;else
a+="_"}a+=")"}else
if(b[0]==i)a+=b[1];return a}function
aJ(b){if(b
instanceof
Array&&(b[0]==0||b[0]==i)){var
d=q("Printexc.handle_uncaught_exception");if(d)d(b,false);else{var
e=a8(b),c=q(ad);if(c)c(0);a.console.error("Fatal error: exception "+e+ay)}}else
throw b}function
bj(){var
b=a;if(b.process&&b.process.on)b.process.on("uncaughtException",function(a,c){aJ(a);b.process.exit(2)});else
if(b.addEventListener)b.addEventListener("error",function(a){if(a.error)aJ(a.error)})}bj();a9();var
W=[i,e(ar),-2],_=[0,e("matt"),e("roberts")];j(11,[i,e(ac),-12],ac);j(10,[i,e($),-11],$);j(9,[i,e(au),-10],au);j(8,[i,e(ak),-9],ak);j(7,[i,e(ag),-8],ag);j(6,[i,e(ah),-7],ah);j(5,[i,e(as),-6],as);j(4,[i,e(az),-5],az);j(3,[i,e(aC),-4],aC);j(2,[i,e(O),-3],O);j(1,W,ar);j(0,[i,e(am),-1],am);var
aY=e(" ");function
X(d,c){var
a=A(d),e=A(c),b=p(a+e|0);P(d,0,b,0,a);P(c,0,b,a,e);return aS(b)}bc(0);var
aX=aO(1);aO(2);function
Y(b){function
a(b){var
a=b;for(;;){if(a){var
c=a[2],d=a[1];try{aN(d)}catch(a){a=bn(a);if(a[1]!==W)throw a;var
e=a}var
a=c;continue}return 0}}return a(bd(0))}bi(e(ad),Y);var
aZ=X(aY,_[2]),Z=X(_[1],aZ);be(aX,Z,0,A(Z));Y(0);return}(globalThis));
